In [5]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'C:\Program Files\Python310\python.exe -m pip install --upgrade pip' command.


In [6]:
import numpy as np
#task 1
array = np.array([0,1,2,3,4,5,6,7,8,9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
#task 2
array = np.array([0,1,2,3,4,5,6,7,8])
array = array.reshape(3,3)
print(array<=8)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [32]:
# task 3
array = np.array([0,1,2,3,4,5,6,7,8,9])
b = array[array % 2 == 1]
print (b)



[1 3 5 7 9]


In [34]:
# task 4
array = np.array([0,1,2,3,4,5,6,7,8,9])
array[array % 2 == 1] = -1

print(array)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [36]:
#tak 5

array = np.array([0,1,2,3])
array = array.reshape(2,2)
print(array)


[[0 1]
 [2 3]]


In [38]:
#task 6 part a
a = np.arange(0,9).reshape(3,3)
b = np.arange(0,9).reshape(3,3)
c = np.dot(a,b)
print(c)

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [51]:
#task 6 part b

a = np.arange(1,5).reshape(2,2)
b = np.arange(1,5).reshape(2,2)
c = np.dot(a,b)
sum = np.sum(c)
print(sum)


54


In [58]:
# EXTENSION PART 1

x = 4
array = np.array([x-3,x-3,x-3,x-2,x-2,x-2,x-1,x-1,x-1,x-3,x-2,x-1,x-3,x-2,x-1])
print(array)



[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3]


In [61]:
# EXTENSION PART 2
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = np.array([10,11,12,13,14,15,16,17,18,19])
a = b
print(a)


[10 11 12 13 14 15 16 17 18 19]


In [67]:
#EXTENSION PART 3
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = np.array([10,11,12,13,14,15,16,17,18,19])
c = (a[3:7],b[3:7])
sum = np.sum(c)
print(sum)

76
